const pokemonsNames = [
    "Caterpie",
    "Metapod",
    "Rattata",
    "Raticate de Alola",
    "Fearow",
    "Pikachu",
    "Clefairy",
    "Golbat",
    "Paras",
    "Diglett de Alola",
    "Meowth",
    "Meowth de Alola",
    "Slowpoke",
    "Shellder",
    "Cloyster",
    "Magikarp",
    "Eevee",
    "Dratini",
    "Dragonair",
    "Snubbull",
    "Skarmory",
    "Makuhita",
    "Gigalith",
    "Whimsicott",
    "Darumaka",
    "Vanillish",
    "Yungoos",
    "Grubbin",
    "Salandit",
    "Stufful",
]

const pokemonsTypes = [
    "Inseto",
    "Inseto",
    "Normal",
    "Sombrio/Normal",
    "Voador/Normal",
    "Elétrico",
    "Fada",
    "Voador/Venenoso",
    "Inseto/Planta",
    "Terrestre/Aço",
    "Normal",
    "Sombrio",
    "Água/Psíquico",
    "Água",
    "Água/Gelo",
    "Água",
    "Normal",
    "Dragão",
    "Dragão",
    "Fada",
    "Voador/Aço",
    "Lutador",
    "Terrestre",
    "Fada/Planta",
    "Fogo",
    "Gelo",
    "Normal",
    "Inseto",
    "Fogo/Venenoso",
    "Lutador/Normal",
]

export { pokemonsNames, pokemonsTypes };